#ifndef ReadHallCData_h
#define ReadHallCData_h

#include <iostream>
#include <string.h>
#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>
#include <TStyle.h>
#include <TCanvas.h>
#include <TVector3.h>
#include <TObject.h>
#include <TFile.h>
#include <fstream>
#include <TGraphAsymmErrors.h>
#include <stdio.h>
#include <stdlib.h>
#include <TMinuit.h>
#include <TDataType.h>
#include <TTree.h>
#include <TFitResult.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TF1.h>
#include <TVector3.h>
#include <TLorentzVector.h>
#include <TLegend.h>
#include <set>
#include <TCanvas.h>
#include <TGraphErrors.h>
#include <TBuffer.h>
#include "Fit/LogLikelihoodFCN.h"
#include "Fit/BinData.h"
#include "Fit/UnBinData.h"
#include "Fit/Fitter.h"
#include "Fit/BinData.h"
#include "HFitInterface.h"
#include "Math/WrappedMultiTF1.h"
#include "HFitInterface.h"
#include "Math/IFunction.h"
 #include "Math/FitMethodFunction.h"
#include <TRandom3.h>
#include <TSpectrum.h>
#include <TVirtualFitter.h>
#include <TList.h>
#include <TDirectory.h>
#include "Utils.h"
#include "ReadTextFiles.h"
#include "Constants.h"
using namespace std;

class ReadHallCData {

   private: 
   
   virtual Int_t GetEntry(Long64_t entry);
   virtual Long64_t LoadTree(Long64_t entry);
   virtual Bool_t Notify();
   Int_t fCurrent; 
   int InitValues();
   int InitBranch();     

   public :

   ReadHallCData();
   ReadHallCData  ( vector <string> files );
   virtual ~ReadHallCData();
   int Init(); 
   virtual void Loop (vector <string> vector_name, int runID, string  process, string what, string target); 
   int InitHist();
   int DeleteHist();
   int DrawHist(string , int);

   TChain *iChain;
   
   // genereric variables	
   int entry, test;
   
   // input variables / database
   float Eb, targetmass, HMS_p_central, SHMS_p_central, HMS_th_central, SHMS_th_central;
   float HMS_B2_cur, SHMS_B2_cur, HMS_B4_cut, SHMS_B4_cut, HMS_B2_cur_cut, SHMS_B2_cur_cut, HMS_live, SHMS_live; 
   float HMS34rates, SHMS34rates, HMS_ST, SHMS_ST, C_T; 
   float HMS_E_eff, HMS_H_eff, SHMS_E_eff, SHMS_H_eff; 
   float HMS_run_l, SHMS_run_l, All_T, lumiexp_HMS, lumiexp_SHMS;

   // for tree out
   int runindex;
   float ALV_el_out_data[4]; 
   float ALV_gamma_out_data[4]; 
   float ALV_pi_out_data[4]; 
   float ALV_proton_out_data[4]; 
   float ALV_neutron_out_data[4]; 
   float ALV_el_in_data[4]; 
   float ALV_proton_in_data[4]; 
   float M2miss_data, Mmiss_data, Emiss_data, PTmiss_data, PT2miss_data, Pmiss_ref_data, Thmiss_ref_data; 
   float Q2_data, epsilon_data, Xbj_data, CosThCM_data, ThCM_data, mt_data, nu_data, W_data, Phi_data; 
   float beta_HMS, beta_SHMS;
   float Q2_kinmod, epsilon_kinmod, Xbj_kinmod, mt_kinmod, W_kinmod, nu_kinmod;
   float HMS_act_time, SHMS_act_time;
   float time_trig1, time_trig2, time_roc1, time_roc2;
   // files
   ofstream outfile, out2, out3;
   ifstream infile; 
   float inc[25];
   string line;
   float LL, hdp_low, hdp_up, sdp_low, sdp_up;
   float th_hms_up, phi_hms_up, th_shms_up, phi_shms_up;
   float hms_cal_en_cut, hms_cer_npe_cut, shms_cal_en_cut;
   float shms_aero_npe_cut, shms_hgcer_npe_cut;
   float trig_time_cut_low, trig_time_cut_up, roc_time_cut_low, roc_time_cut_up, time_shift;
   float hms_beta_min, hms_beta_max, shms_beta_min, shms_beta_max;
   // only in the code
   TLorentzVector LV_virtual, LV_el_out_data, LV_gamma_out_data, LV_proton_out_data, LV_el_in_data, LV_proton_in_data;
   TVector3 V_Normal_Mu, V_Normal_Final;
   float Egout_CMeP, PinCM, PoutCM;

   // histograms
   TH1F *h_CTime_epCoinTime_ROC1[5], *h_CTime_epCoinTime_ROC2[5], *h_CTime_epCoinTime_TRIG1[5], *h_CTime_epCoinTime_TRIG2[5];
   TH1F *h_Pmom[5], *h_elmom[5], *h_gmom[5], *h_CTime_epCoinTime_ROC2_large[5];
   TH1F *h_Mmiss[5], *h_M2miss[5], *h_Emiss[5], *h_PTmiss[5], *h_PT2miss[5]; 
   TH1F *h_Q2[5], *h_epsilon[5], *h_Xbj[5], *h_CosThCM[5], *h_ThCM[5], *h_mt[5], *h_W[5], *h_Phi[5], *h_nu[5]; 
   TH2F *h2_Pemom[5], *h2_elemom[5], *h2_gemom[5];
   TH2F *h2_elebeta[5], *h2_Pebeta[5], *h2_COIN_P_beta[5], *h2_COIN_H_beta[5];
   TH2F *h2_Q2W[5], *h2_XQ2[5], *h2_Q2mt[5], *h2_ThCMPhi[5], *h2_nuep[5], *h2_Q2Th[5], *h2_WTh[5], *h2_mtTh[5];
   TH2F *h2_M2miss_CT1[5], *h2_M2miss_CT2[5];

   TH1F *h_encal_hms, *h_cer_npe_hms, *h_aero_npe_shms, *h_hgcer_npe_shms;
   TH1F *h_delta_hms, *h_delta_shms, *h_phi_hms, *h_theta_hms, *h_phi_shms, *h_theta_shms;
   TH2F *h2_encal_cer, *h2_aero_hgcer_npe;

   // for tree in  
   double H_gtr_xptar                ;
   double H_gtr_yptar                ;
   double P_gtr_xptar                ;
   double P_gtr_yptar                ;
   double mmiss                      ;
   double CTime_epCoinTime_ROC1      ;                     
   double CTime_epCoinTime_ROC2      ;                     
   double CTime_epCoinTime_TRIG1     ;                     
   double CTime_epCoinTime_TRIG4     ;                     
   double H_cal_eprtrack             ;                
   double H_cal_eprtracknorm         ;                
   double H_cal_etot                 ;                
   double H_cal_etotnorm             ;                
   double H_cal_etottracknorm        ;                
   double H_cal_etrack               ;                
   double H_cal_etracknorm           ;                
   double H_cer_npeSum               ;                
   double H_dc_ntrack                ;                
   double H_dc_x_fp                  ;                
   double H_dc_xp_fp                 ;                
   double H_dc_y_fp                  ;                
   double H_dc_yp_fp                 ;                
   double H_extcor_xsieve            ;                
   double H_extcor_ysieve            ;                
   double H_gtr_beta                 ;                
   double H_gtr_dp                   ;                
   double H_gtr_index                ;                
   double H_gtr_ok                   ;                
   double H_gtr_p                    ;                
   double H_gtr_ph                   ;                
   double H_gtr_px                   ;                
   double H_gtr_py                   ;                
   double H_gtr_pz                   ;                
   double H_gtr_th                   ;                
   double H_gtr_x                    ;                
   double H_gtr_y                    ;                
   double H_hod_beta                 ;                
   double H_hod_betachisqnotrack     ;               
   double H_hod_betanotrack          ;               
   double H_hod_fpHitsTime           ;               
   double H_hod_starttime            ;               
   double H_kin_primary_Q2           ;               
   double H_kin_primary_W            ;               
   double H_kin_primary_W2           ;               
   double H_kin_primary_epsilon      ;               
   double H_kin_primary_nu           ;               
   double H_kin_primary_omega        ;               
   double H_kin_primary_ph_q         ;               
   double H_kin_primary_q3m          ;               
   double H_kin_primary_q_x          ;               
   double H_kin_primary_q_y          ;               
   double H_kin_primary_q_z          ;              
   double H_kin_primary_scat_ang_deg ;               
   double H_kin_primary_scat_ang_rad ;              
   double H_kin_primary_th_q         ;             
   double H_kin_primary_x_bj         ;            
   double H_rb_raster_fr_xbpm_tar    ;              
   double H_rb_raster_fr_ybpm_tar    ;              
   double H_react_x                  ;           
   double H_react_y                  ;           
   double H_react_z                  ;           
   double P_aero_npeSum              ;          
   double P_cal_eprtrack             ;          
   double P_cal_eprtracknorm         ;          
   double P_cal_etot                 ;          
   double P_cal_etotnorm             ;          
   double P_cal_etottracknorm        ;          
   double P_cal_etracknorm           ;          
   double P_cal_pr_eplane            ;          
   double P_dc_ntrack                ;          
   double P_dc_x_fp                  ;          
   double P_dc_xp_fp                 ;          
   double P_dc_y_fp                  ;          
   double P_dc_yp_fp                 ;          
   double P_extcor_xsieve            ;          
   double P_extcor_ysieve            ;          
   double P_gtr_beta                 ;          
   double P_gtr_dp                   ;          
   double P_gtr_index                ;         
   double P_gtr_ok                   ;         
   double P_gtr_p                    ;         
   double P_gtr_ph                   ;         
   double P_gtr_px                   ;         
   double P_gtr_py                   ;         
   double P_gtr_pz                   ;         
   double P_gtr_th                   ;         
   double P_gtr_x                    ;         
   double P_gtr_y                    ;         
   double P_hgcer_npeSum             ;         
   double P_hod_beta                 ;         
   double P_hod_betachisqnotrack     ;         
   double P_hod_betanotrack          ;        
   double P_hod_fpHitsTime           ;        
   double P_hod_goodscinhit          ;        
   double P_hod_starttime            ;        
   double P_kin_secondary_Erecoil    ;        
   double P_kin_secondary_MandelS    ;        
   double P_kin_secondary_MandelT    ;        
   double P_kin_secondary_MandelU    ;        
   double P_kin_secondary_Mrecoil    ;        
   double P_kin_secondary_Prec_x     ;        
   double P_kin_secondary_Prec_y     ;        
   double P_kin_secondary_Prec_z     ;        
   double P_kin_secondary_emiss      ;        
   double P_kin_secondary_emiss_nuc  ;        
   double P_kin_secondary_ph_bq      ;              
   double P_kin_secondary_ph_xq      ;              
   double P_kin_secondary_phb_cm     ;              
   double P_kin_secondary_phx_cm     ;              
   double P_kin_secondary_pmiss      ;              
   double P_kin_secondary_pmiss_x    ;              
   double P_kin_secondary_pmiss_y    ;              
   double P_kin_secondary_pmiss_z    ;              
   double P_kin_secondary_px_cm      ;              
   double P_kin_secondary_t_tot_cm   ;              
   double P_kin_secondary_tb         ;              
   double P_kin_secondary_tb_cm      ;              
   double P_kin_secondary_th_bq      ;              
   double P_kin_secondary_th_xq      ;              
   double P_kin_secondary_thb_cm     ;              
   double P_kin_secondary_thx_cm     ;              
   double P_kin_secondary_tx         ;              
   double P_kin_secondary_tx_cm      ;              
   double P_kin_secondary_xangle     ;              
   double P_ngcer_npeSum             ;              
   double P_react_z                  ;              
   double T_coin_h1T_tdcMultiplicity ;              
   double T_coin_h1T_tdcTime         ;              
   double T_coin_h1T_tdcTimeRaw      ;              
   double T_coin_h1X_tdcMultiplicity ;              
   double T_coin_h1X_tdcTime         ;              
   double T_coin_h1X_tdcTimeRaw      ;              
   double T_coin_h1Y_tdcMultiplicity ;              
   double T_coin_h1Y_tdcTime         ;              
   double T_coin_h1Y_tdcTimeRaw      ;              
   double T_coin_h2T_tdcMultiplicity ;              
   double T_coin_h2T_tdcTime         ;              
   double T_coin_h2T_tdcTimeRaw      ;              
   double T_coin_h2X_tdcMultiplicity ;              
   double T_coin_h2X_tdcTime         ;              
   double T_coin_h2X_tdcTimeRaw      ;              
   double T_coin_h2Y_tdcMultiplicity ;              
   double T_coin_h2Y_tdcTime         ;              
   double T_coin_h2Y_tdcTimeRaw      ;              
   double T_coin_hAER_adcMultiplicity;              
   double T_coin_hAER_adcPed         ;             
   double T_coin_hAER_adcPedRaw      ;             
   double T_coin_hAER_adcPulseAmp    ;             
   double T_coin_hAER_adcPulseAmpRaw ;             
   double T_coin_hAER_adcPulseInt    ;             
   double T_coin_hAER_adcPulseIntRaw ;             
   double T_coin_hAER_adcPulseTime   ;             
   double T_coin_hAER_adcPulseTimeRaw;             
   double T_coin_hASUM_adcMultiplicity;            
   double T_coin_hASUM_adcPed         ;            
   double T_coin_hASUM_adcPedRaw      ;            
   double T_coin_hASUM_adcPulseAmp    ;            
   double T_coin_hASUM_adcPulseAmpRaw ;            
   double T_coin_hASUM_adcPulseInt    ;            
   double T_coin_hASUM_adcPulseIntRaw ;            
   double T_coin_hASUM_adcPulseTime   ;            
   double T_coin_hASUM_adcPulseTimeRaw;            
   double T_coin_hASUM_tdcMultiplicity;            
   double T_coin_hASUM_tdcTime        ;            
   double T_coin_hASUM_tdcTimeRaw     ;            
   double T_coin_hBSUM_adcMultiplicity;            
   double T_coin_hBSUM_adcPed         ;           
   double T_coin_hBSUM_adcPedRaw      ;           
   double T_coin_hBSUM_adcPulseAmp    ;           
   double T_coin_hBSUM_adcPulseAmpRaw ;           
   double T_coin_hBSUM_adcPulseInt    ;           
   double T_coin_hBSUM_adcPulseIntRaw ;           
   double T_coin_hBSUM_adcPulseTime   ;           
   double T_coin_hBSUM_adcPulseTimeRaw;           
   double T_coin_hBSUM_tdcMultiplicity;           
   double T_coin_hBSUM_tdcTime        ;           
   double T_coin_hBSUM_tdcTimeRaw     ;           
   double T_coin_hCER_adcMultiplicity ;           
   double T_coin_hCER_adcPed          ;           
   double T_coin_hCER_adcPedRaw       ;           
   double T_coin_hCER_adcPulseAmp     ;           
   double T_coin_hCER_adcPulseAmpRaw  ;           
   double T_coin_hCER_adcPulseInt     ;           
   double T_coin_hCER_adcPulseIntRaw  ;           
   double T_coin_hCER_adcPulseTime    ;           
   double T_coin_hCER_adcPulseTimeRaw ;           
   double T_coin_hCER_tdcMultiplicity ;          
   double T_coin_hCER_tdcTime         ;          
   double T_coin_hCER_tdcTimeRaw      ;          
   double T_coin_hCSUM_adcMultiplicity;          
   double T_coin_hCSUM_adcPed         ;          
   double T_coin_hCSUM_adcPedRaw      ;          
   double T_coin_hCSUM_adcPulseAmp    ;          
   double T_coin_hCSUM_adcPulseAmpRaw ;          
   double T_coin_hCSUM_adcPulseInt    ;          
   double T_coin_hCSUM_adcPulseIntRaw ;          
   double T_coin_hCSUM_adcPulseTime   ;          
   double T_coin_hCSUM_adcPulseTimeRaw;          
   double T_coin_hCSUM_tdcMultiplicity;          
   double T_coin_hCSUM_tdcTime        ;          
   double T_coin_hCSUM_tdcTimeRaw     ;          
   double T_coin_hDCREF1_tdcMultiplicity;         
   double T_coin_hDCREF1_tdcTime        ;         
   double T_coin_hDCREF1_tdcTimeRaw     ;         
   double T_coin_hDCREF2_tdcMultiplicity;         
   double T_coin_hDCREF2_tdcTime        ;         
   double T_coin_hDCREF2_tdcTimeRaw     ;         
   double T_coin_hDCREF3_tdcMultiplicity;         
   double T_coin_hDCREF3_tdcTime        ;         
   double T_coin_hDCREF3_tdcTimeRaw     ;         
   double T_coin_hDCREF4_tdcMultiplicity;         
   double T_coin_hDCREF4_tdcTime        ;         
   double T_coin_hDCREF4_tdcTimeRaw     ;         
   double T_coin_hDCREF5_tdcMultiplicity;         
   double T_coin_hDCREF5_tdcTime        ;        
   double T_coin_hDCREF5_tdcTimeRaw     ;        
   double T_coin_hDSUM_adcMultiplicity  ;        
   double T_coin_hDSUM_adcPed           ;        
   double T_coin_hDSUM_adcPedRaw        ;        
   double T_coin_hDSUM_adcPulseAmp      ;        
   double T_coin_hDSUM_adcPulseAmpRaw   ;        
   double T_coin_hDSUM_adcPulseInt      ;        
   double T_coin_hDSUM_adcPulseIntRaw   ;        
   double T_coin_hDSUM_adcPulseTime     ;        
   double T_coin_hDSUM_adcPulseTimeRaw  ;        
   double T_coin_hDSUM_tdcMultiplicity  ;        
   double T_coin_hDSUM_tdcTime          ;        
   double T_coin_hDSUM_tdcTimeRaw       ;        
   double T_coin_hEDTM_tdcMultiplicity  ;        
   double T_coin_hEDTM_tdcTime          ;        
   double T_coin_hEDTM_tdcTimeRaw       ;        
   double T_coin_hEL_CLEAN_ROC1_tdcMultiplicity ;
   double T_coin_hEL_CLEAN_ROC1_tdcTime         ;
   double T_coin_hEL_CLEAN_ROC1_tdcTimeRaw      ;
   double T_coin_hEL_CLEAN_ROC2_tdcMultiplicity ;
   double T_coin_hEL_CLEAN_ROC2_tdcTime         ;
   double T_coin_hEL_CLEAN_ROC2_tdcTimeRaw      ;
   double T_coin_hEL_HI_ROC1_tdcMultiplicity    ;
   double T_coin_hEL_HI_ROC1_tdcTime            ;
   double T_coin_hEL_HI_ROC1_tdcTimeRaw         ;
   double T_coin_hEL_HI_ROC2_tdcMultiplicity    ;
   double T_coin_hEL_HI_ROC2_tdcTime            ;
   double T_coin_hEL_HI_ROC2_tdcTimeRaw         ;
   double T_coin_hEL_LO_LO_ROC1_tdcMultiplicity ;
   double T_coin_hEL_LO_LO_ROC1_tdcTime         ;
   double T_coin_hEL_LO_LO_ROC1_tdcTimeRaw      ;
   double T_coin_hEL_LO_LO_ROC2_tdcMultiplicity ;
   double T_coin_hEL_LO_LO_ROC2_tdcTime         ;
   double T_coin_hEL_LO_LO_ROC2_tdcTimeRaw      ;
   double T_coin_hEL_LO_ROC1_tdcMultiplicity    ;
   double T_coin_hEL_LO_ROC1_tdcTime            ;
   double T_coin_hEL_LO_ROC1_tdcTimeRaw         ;
   double T_coin_hEL_LO_ROC2_tdcMultiplicity    ;
   double T_coin_hEL_LO_ROC2_tdcTime            ;
   double T_coin_hEL_LO_ROC2_tdcTimeRaw         ;
   double T_coin_hEL_REAL_ROC1_tdcMultiplicity  ;
   double T_coin_hEL_REAL_ROC1_tdcTime          ;   
   double T_coin_hEL_REAL_ROC1_tdcTimeRaw       ;   
   double T_coin_hEL_REAL_ROC2_tdcMultiplicity  ;   
   double T_coin_hEL_REAL_ROC2_tdcTime          ;   
   double T_coin_hEL_REAL_ROC2_tdcTimeRaw       ;   
   double T_coin_hFADC_TREF_ROC1_adcMultiplicity;   
   double T_coin_hFADC_TREF_ROC1_adcPed         ;   
   double T_coin_hFADC_TREF_ROC1_adcPedRaw      ;   
   double T_coin_hFADC_TREF_ROC1_adcPulseAmp    ;   
   double T_coin_hFADC_TREF_ROC1_adcPulseAmpRaw ;   
   double T_coin_hFADC_TREF_ROC1_adcPulseInt    ;   
   double T_coin_hFADC_TREF_ROC1_adcPulseIntRaw ;   
   double T_coin_hFADC_TREF_ROC1_adcPulseTime   ;   
   double T_coin_hFADC_TREF_ROC1_adcPulseTimeRaw;   
   double T_coin_hHODO_RF_tdcMultiplicity       ;   
   double T_coin_hHODO_RF_tdcTime               ;   
   double T_coin_hHODO_RF_tdcTimeRaw            ;   
   double T_coin_hPRE100_ROC1_tdcMultiplicity   ;   
   double T_coin_hPRE100_ROC1_tdcTime           ;   
   double T_coin_hPRE100_ROC1_tdcTimeRaw        ;   
   double T_coin_hPRE100_ROC2_tdcMultiplicity   ;   
   double T_coin_hPRE100_ROC2_tdcTime           ;   
   double T_coin_hPRE100_ROC2_tdcTimeRaw        ;   
   double T_coin_hPRE150_ROC1_tdcMultiplicity   ;   
   double T_coin_hPRE150_ROC1_tdcTime           ;   
   double T_coin_hPRE150_ROC1_tdcTimeRaw        ;   
   double T_coin_hPRE150_ROC2_tdcMultiplicity   ;   
   double T_coin_hPRE150_ROC2_tdcTime           ;   
   double T_coin_hPRE150_ROC2_tdcTimeRaw        ;   
   double T_coin_hPRE200_ROC1_tdcMultiplicity   ;   
   double T_coin_hPRE200_ROC1_tdcTime           ;   
   double T_coin_hPRE200_ROC1_tdcTimeRaw        ;   
   double T_coin_hPRE200_ROC2_tdcMultiplicity   ;   
   double T_coin_hPRE200_ROC2_tdcTime           ;   
   double T_coin_hPRE200_ROC2_tdcTimeRaw        ;   
   double T_coin_hPRE40_ROC1_tdcMultiplicity    ;   
   double T_coin_hPRE40_ROC1_tdcTime            ;  
   double T_coin_hPRE40_ROC1_tdcTimeRaw         ;  
   double T_coin_hPRE40_ROC2_tdcMultiplicity    ;  
   double T_coin_hPRE40_ROC2_tdcTime            ;  
   double T_coin_hPRE40_ROC2_tdcTimeRaw         ;  
   double T_coin_hPRHI_tdcMultiplicity          ;  
   double T_coin_hPRHI_tdcTime                  ;  
   double T_coin_hPRHI_tdcTimeRaw               ;  
   double T_coin_hPRLO_tdcMultiplicity          ;  
   double T_coin_hPRLO_tdcTime                  ;  
   double T_coin_hPRLO_tdcTimeRaw               ;  
   double T_coin_hPSHWR_adcMultiplicity         ;  
   double T_coin_hPSHWR_adcPed                  ;  
   double T_coin_hPSHWR_adcPedRaw               ;  
   double T_coin_hPSHWR_adcPulseAmp             ;  
   double T_coin_hPSHWR_adcPulseAmpRaw          ;  
   double T_coin_hPSHWR_adcPulseInt             ;  
   double T_coin_hPSHWR_adcPulseIntRaw          ;  
   double T_coin_hPSHWR_adcPulseTime            ;  
   double T_coin_hPSHWR_adcPulseTimeRaw         ;  
   double T_coin_hRF_tdcMultiplicity            ;  
   double T_coin_hRF_tdcTime                    ;  
   double T_coin_hRF_tdcTimeRaw                 ;  
   double T_coin_hSHWR_adcMultiplicity          ;  
   double T_coin_hSHWR_adcPed                   ;  
   double T_coin_hSHWR_adcPedRaw                ;  
   double T_coin_hSHWR_adcPulseAmp              ;  
   double T_coin_hSHWR_adcPulseAmpRaw           ;  
   double T_coin_hSHWR_adcPulseInt              ;  
   double T_coin_hSHWR_adcPulseIntRaw           ;  
   double T_coin_hSHWR_adcPulseTime             ;  
   double T_coin_hSHWR_adcPulseTimeRaw          ;  
   double T_coin_hSHWR_tdcMultiplicity          ;  
   double T_coin_hSHWR_tdcTime                  ;  
   double T_coin_hSHWR_tdcTimeRaw               ;  
   double T_coin_hSTOF_ROC1_tdcMultiplicity     ;  
   double T_coin_hSTOF_ROC1_tdcTime             ;  
   double T_coin_hSTOF_ROC1_tdcTimeRaw          ;  
   double T_coin_hSTOF_ROC2_tdcMultiplicity     ;  
   double T_coin_hSTOF_ROC2_tdcTime             ; 
   double T_coin_hSTOF_ROC2_tdcTimeRaw          ; 
   double T_coin_hT1_tdcMultiplicity            ; 
   double T_coin_hT1_tdcTime                    ; 
   double T_coin_hT1_tdcTimeRaw                 ; 
   double T_coin_hT2_tdcMultiplicity            ; 
   double T_coin_hT2_tdcTime                    ; 
   double T_coin_hT2_tdcTimeRaw                 ; 
   double T_coin_hTRIG1_ROC1_tdcMultiplicity    ; 
   double T_coin_hTRIG1_ROC1_tdcTime            ; 
   double T_coin_hTRIG1_ROC1_tdcTimeRaw         ; 
   double T_coin_hTRIG1_ROC2_tdcMultiplicity    ; 
   double T_coin_hTRIG1_ROC2_tdcTime            ; 
   double T_coin_hTRIG1_ROC2_tdcTimeRaw         ; 
   double T_coin_hTRIG2_ROC1_tdcMultiplicity    ; 
   double T_coin_hTRIG2_ROC1_tdcTime            ; 
   double T_coin_hTRIG2_ROC1_tdcTimeRaw         ; 
   double T_coin_hTRIG2_ROC2_tdcMultiplicity    ; 
   double T_coin_hTRIG2_ROC2_tdcTime            ; 
   double T_coin_hTRIG2_ROC2_tdcTimeRaw         ; 
   double T_coin_hTRIG3_ROC1_tdcMultiplicity    ; 
   double T_coin_hTRIG3_ROC1_tdcTime            ; 
   double T_coin_hTRIG3_ROC1_tdcTimeRaw         ; 
   double T_coin_hTRIG3_ROC2_tdcMultiplicity    ; 
   double T_coin_hTRIG3_ROC2_tdcTime            ; 
   double T_coin_hTRIG3_ROC2_tdcTimeRaw         ; 
   double T_coin_hTRIG4_ROC1_tdcMultiplicity    ; 
   double T_coin_hTRIG4_ROC1_tdcTime            ; 
   double T_coin_hTRIG4_ROC1_tdcTimeRaw         ; 
   double T_coin_hTRIG4_ROC2_tdcMultiplicity    ; 
   double T_coin_hTRIG4_ROC2_tdcTime            ; 
   double T_coin_hTRIG4_ROC2_tdcTimeRaw         ; 
   double T_coin_hTRIG5_ROC1_tdcMultiplicity    ; 
   double T_coin_hTRIG5_ROC1_tdcTime            ; 
   double T_coin_hTRIG5_ROC1_tdcTimeRaw         ; 
   double T_coin_hTRIG5_ROC2_tdcMultiplicity    ; 
   double T_coin_hTRIG5_ROC2_tdcTime            ; 
   double T_coin_hTRIG5_ROC2_tdcTimeRaw         ; 
   double T_coin_hTRIG6_ROC1_tdcMultiplicity    ; 
   double T_coin_hTRIG6_ROC1_tdcTime            ; 
   double T_coin_hTRIG6_ROC1_tdcTimeRaw         ; 
   double T_coin_hTRIG6_ROC2_tdcMultiplicity    ; 
   double T_coin_hTRIG6_ROC2_tdcTime            ;
   double T_coin_hTRIG6_ROC2_tdcTimeRaw         ;
   double T_coin_p1T_tdcMultiplicity            ;
   double T_coin_p1T_tdcTime                    ;
   double T_coin_p1T_tdcTimeRaw                 ;
   double T_coin_p1X_tdcMultiplicity            ;
   double T_coin_p1X_tdcTime                    ;
   double T_coin_p1X_tdcTimeRaw                 ;
   double T_coin_p1Y_tdcMultiplicity            ;
   double T_coin_p1Y_tdcTime                    ;
   double T_coin_p1Y_tdcTimeRaw                 ;
   double T_coin_p2T_tdcMultiplicity            ;
   double T_coin_p2T_tdcTime                    ;
   double T_coin_p2T_tdcTimeRaw                 ;
   double T_coin_p2X_tdcMultiplicity            ;
   double T_coin_p2X_tdcTime                    ;
   double T_coin_p2X_tdcTimeRaw                 ;
   double T_coin_p2Y_tdcMultiplicity            ;
   double T_coin_p2Y_tdcTime                    ;
   double T_coin_p2Y_tdcTimeRaw                 ;
   double T_coin_pAER_adcMultiplicity           ;
   double T_coin_pAER_adcPed                    ;
   double T_coin_pAER_adcPedRaw                 ;
   double T_coin_pAER_adcPulseAmp               ;
   double T_coin_pAER_adcPulseAmpRaw            ;
   double T_coin_pAER_adcPulseInt               ;
   double T_coin_pAER_adcPulseIntRaw            ;
   double T_coin_pAER_adcPulseTime              ;
   double T_coin_pAER_adcPulseTimeRaw           ;
   double T_coin_pAER_tdcMultiplicity           ;
   double T_coin_pAER_tdcTime                   ;
   double T_coin_pAER_tdcTimeRaw                ;
   double T_coin_pDCREF10_tdcMultiplicity       ;
   double T_coin_pDCREF10_tdcTime               ;
   double T_coin_pDCREF10_tdcTimeRaw            ;
   double T_coin_pDCREF1_tdcMultiplicity        ;
   double T_coin_pDCREF1_tdcTime                ;
   double T_coin_pDCREF1_tdcTimeRaw             ;
   double T_coin_pDCREF2_tdcMultiplicity        ;
   double T_coin_pDCREF2_tdcTime                ;
   double T_coin_pDCREF2_tdcTimeRaw             ;
   double T_coin_pDCREF3_tdcMultiplicity        ;
   double T_coin_pDCREF3_tdcTime                ;
   double T_coin_pDCREF3_tdcTimeRaw             ;
   double T_coin_pDCREF4_tdcMultiplicity        ;
   double T_coin_pDCREF4_tdcTime                ;
   double T_coin_pDCREF4_tdcTimeRaw             ;
   double T_coin_pDCREF5_tdcMultiplicity        ;
   double T_coin_pDCREF5_tdcTime                ;
   double T_coin_pDCREF5_tdcTimeRaw             ;
   double T_coin_pDCREF6_tdcMultiplicity        ;
   double T_coin_pDCREF6_tdcTime                ;
   double T_coin_pDCREF6_tdcTimeRaw             ;
   double T_coin_pDCREF7_tdcMultiplicity        ;
   double T_coin_pDCREF7_tdcTime                ;
   double T_coin_pDCREF7_tdcTimeRaw             ;
   double T_coin_pDCREF8_tdcMultiplicity        ;
   double T_coin_pDCREF8_tdcTime                ;
   double T_coin_pDCREF8_tdcTimeRaw             ;
   double T_coin_pDCREF9_tdcMultiplicity        ;
   double T_coin_pDCREF9_tdcTime                ;
   double T_coin_pDCREF9_tdcTimeRaw             ;
   double T_coin_pEDTM_tdcMultiplicity          ;
   double T_coin_pEDTM_tdcTime                  ;
   double T_coin_pEDTM_tdcTimeRaw               ;
   double T_coin_pEL_CLEAN_ROC1_tdcMultiplicity ;
   double T_coin_pEL_CLEAN_ROC1_tdcTime         ;        
   double T_coin_pEL_CLEAN_ROC1_tdcTimeRaw      ;        
   double T_coin_pEL_CLEAN_ROC2_tdcMultiplicity ;        
   double T_coin_pEL_CLEAN_ROC2_tdcTime         ;        
   double T_coin_pEL_CLEAN_ROC2_tdcTimeRaw      ;        
   double T_coin_pEL_HI_ROC1_tdcMultiplicity    ;        
   double T_coin_pEL_HI_ROC1_tdcTime            ;        
   double T_coin_pEL_HI_ROC1_tdcTimeRaw         ;        
   double T_coin_pEL_HI_ROC2_tdcMultiplicity    ;        
   double T_coin_pEL_HI_ROC2_tdcTime            ;        
   double T_coin_pEL_HI_ROC2_tdcTimeRaw         ;        
   double T_coin_pEL_LO_LO_ROC1_tdcMultiplicity ;        
   double T_coin_pEL_LO_LO_ROC1_tdcTime         ;        
   double T_coin_pEL_LO_LO_ROC1_tdcTimeRaw      ;        
   double T_coin_pEL_LO_LO_ROC2_tdcMultiplicity ;        
   double T_coin_pEL_LO_LO_ROC2_tdcTime         ;        
   double T_coin_pEL_LO_LO_ROC2_tdcTimeRaw      ;        
   double T_coin_pEL_LO_ROC1_tdcMultiplicity    ;        
   double T_coin_pEL_LO_ROC1_tdcTime            ;        
   double T_coin_pEL_LO_ROC1_tdcTimeRaw         ;        
   double T_coin_pEL_LO_ROC2_tdcMultiplicity    ;        
   double T_coin_pEL_LO_ROC2_tdcTime            ;        
   double T_coin_pEL_LO_ROC2_tdcTimeRaw         ;        
   double T_coin_pEL_REAL_ROC1_tdcMultiplicity  ;        
   double T_coin_pEL_REAL_ROC1_tdcTime          ;        
   double T_coin_pEL_REAL_ROC1_tdcTimeRaw       ;        
   double T_coin_pEL_REAL_ROC2_tdcMultiplicity  ;        
   double T_coin_pEL_REAL_ROC2_tdcTime          ;        
   double T_coin_pEL_REAL_ROC2_tdcTimeRaw       ;        
   double T_coin_pFADC_TREF_ROC2_adcMultiplicity;        
   double T_coin_pFADC_TREF_ROC2_adcPed         ;        
   double T_coin_pFADC_TREF_ROC2_adcPedRaw      ;        
   double T_coin_pFADC_TREF_ROC2_adcPulseAmp    ;        
   double T_coin_pFADC_TREF_ROC2_adcPulseAmpRaw ;        
   double T_coin_pFADC_TREF_ROC2_adcPulseInt    ;        
   double T_coin_pFADC_TREF_ROC2_adcPulseIntRaw ;        
   double T_coin_pFADC_TREF_ROC2_adcPulseTime   ;        
   double T_coin_pFADC_TREF_ROC2_adcPulseTimeRaw;        
   double T_coin_pHEL_MPS_adcMultiplicity       ;       
   double T_coin_pHEL_MPS_adcPed                ;       
   double T_coin_pHEL_MPS_adcPedRaw             ;       
   double T_coin_pHEL_MPS_adcPulseAmp           ;       
   double T_coin_pHEL_MPS_adcPulseAmpRaw        ;       
   double T_coin_pHEL_MPS_adcPulseInt           ;       
   double T_coin_pHEL_MPS_adcPulseIntRaw        ;       
   double T_coin_pHEL_MPS_adcPulseTime          ;       
   double T_coin_pHEL_MPS_adcPulseTimeRaw       ;       
   double T_coin_pHEL_NEG_adcMultiplicity       ;       
   double T_coin_pHEL_NEG_adcPed                ;       
   double T_coin_pHEL_NEG_adcPedRaw             ;       
   double T_coin_pHEL_NEG_adcPulseAmp           ;       
   double T_coin_pHEL_NEG_adcPulseAmpRaw        ;       
   double T_coin_pHEL_NEG_adcPulseInt           ;       
   double T_coin_pHEL_NEG_adcPulseIntRaw        ;       
   double T_coin_pHEL_NEG_adcPulseTime          ;       
   double T_coin_pHEL_NEG_adcPulseTimeRaw       ;       
   double T_coin_pHEL_POS_adcMultiplicity       ;       
   double T_coin_pHEL_POS_adcPed                ;       
   double T_coin_pHEL_POS_adcPedRaw             ;       
   double T_coin_pHEL_POS_adcPulseAmp           ;       
   double T_coin_pHEL_POS_adcPulseAmpRaw        ;       
   double T_coin_pHEL_POS_adcPulseInt           ;       
   double T_coin_pHEL_POS_adcPulseIntRaw        ;       
   double T_coin_pHEL_POS_adcPulseTime          ;       
   double T_coin_pHEL_POS_adcPulseTimeRaw       ;       
   double T_coin_pHGCER_MOD_adcMultiplicity     ;       
   double T_coin_pHGCER_MOD_adcPed              ;       
   double T_coin_pHGCER_MOD_adcPedRaw           ;       
   double T_coin_pHGCER_MOD_adcPulseAmp         ;       
   double T_coin_pHGCER_MOD_adcPulseAmpRaw      ;       
   double T_coin_pHGCER_MOD_adcPulseInt         ;       
   double T_coin_pHGCER_MOD_adcPulseIntRaw      ;       
   double T_coin_pHGCER_MOD_adcPulseTime        ;       
   double T_coin_pHGCER_MOD_adcPulseTimeRaw     ;       
   double T_coin_pHGCER_adcMultiplicity         ;      
   double T_coin_pHGCER_adcPed                  ;      
   double T_coin_pHGCER_adcPedRaw               ;      
   double T_coin_pHGCER_adcPulseAmp             ;      
   double T_coin_pHGCER_adcPulseAmpRaw          ;      
   double T_coin_pHGCER_adcPulseInt             ;      
   double T_coin_pHGCER_adcPulseIntRaw          ;      
   double T_coin_pHGCER_adcPulseTime            ;      
   double T_coin_pHGCER_adcPulseTimeRaw         ;      
   double T_coin_pHGCER_tdcMultiplicity         ;      
   double T_coin_pHGCER_tdcTime                 ;      
   double T_coin_pHGCER_tdcTimeRaw              ;      
   double T_coin_pHODO_RF_tdcMultiplicity       ;      
   double T_coin_pHODO_RF_tdcTime               ;      
   double T_coin_pHODO_RF_tdcTimeRaw            ;      
   double T_coin_pNGCER_MOD_adcMultiplicity     ;      
   double T_coin_pNGCER_MOD_adcPed              ;      
   double T_coin_pNGCER_MOD_adcPedRaw           ;      
   double T_coin_pNGCER_MOD_adcPulseAmp         ;      
   double T_coin_pNGCER_MOD_adcPulseAmpRaw      ;      
   double T_coin_pNGCER_MOD_adcPulseInt         ;      
   double T_coin_pNGCER_MOD_adcPulseIntRaw      ;      
   double T_coin_pNGCER_MOD_adcPulseTime        ;      
   double T_coin_pNGCER_MOD_adcPulseTimeRaw     ;      
   double T_coin_pNGCER_adcMultiplicity         ;      
   double T_coin_pNGCER_adcPed                  ;      
   double T_coin_pNGCER_adcPedRaw               ;      
   double T_coin_pNGCER_adcPulseAmp             ;      
   double T_coin_pNGCER_adcPulseAmpRaw          ;      
   double T_coin_pNGCER_adcPulseInt             ;      
   double T_coin_pNGCER_adcPulseIntRaw          ;      
   double T_coin_pNGCER_adcPulseTime            ;      
   double T_coin_pNGCER_adcPulseTimeRaw         ;      
   double T_coin_pNGCER_tdcMultiplicity         ;      
   double T_coin_pNGCER_tdcTime                 ;      
   double T_coin_pNGCER_tdcTimeRaw              ;      
   double T_coin_pPRE100_ROC1_tdcMultiplicity   ;      
   double T_coin_pPRE100_ROC1_tdcTime           ;      
   double T_coin_pPRE100_ROC1_tdcTimeRaw        ;      
   double T_coin_pPRE100_ROC2_tdcMultiplicity   ;      
   double T_coin_pPRE100_ROC2_tdcTime           ;      
   double T_coin_pPRE100_ROC2_tdcTimeRaw        ;      
   double T_coin_pPRE150_ROC1_tdcMultiplicity   ;      
   double T_coin_pPRE150_ROC1_tdcTime           ;      
   double T_coin_pPRE150_ROC1_tdcTimeRaw        ;      
   double T_coin_pPRE150_ROC2_tdcMultiplicity   ;      
   double T_coin_pPRE150_ROC2_tdcTime           ;      
   double T_coin_pPRE150_ROC2_tdcTimeRaw        ;      
   double T_coin_pPRE200_ROC1_tdcMultiplicity   ;      
   double T_coin_pPRE200_ROC1_tdcTime           ;      
   double T_coin_pPRE200_ROC1_tdcTimeRaw        ;      
   double T_coin_pPRE200_ROC2_tdcMultiplicity   ;      
   double T_coin_pPRE200_ROC2_tdcTime           ;      
   double T_coin_pPRE200_ROC2_tdcTimeRaw        ;      
   double T_coin_pPRE40_ROC1_tdcMultiplicity    ;      
   double T_coin_pPRE40_ROC1_tdcTime            ;     
   double T_coin_pPRE40_ROC1_tdcTimeRaw         ;     
   double T_coin_pPRE40_ROC2_tdcMultiplicity    ;     
   double T_coin_pPRE40_ROC2_tdcTime            ;     
   double T_coin_pPRE40_ROC2_tdcTimeRaw         ;     
   double T_coin_pPRHI_tdcMultiplicity          ;     
   double T_coin_pPRHI_tdcTime                  ;     
   double T_coin_pPRHI_tdcTimeRaw               ;     
   double T_coin_pPRLO_tdcMultiplicity          ;     
   double T_coin_pPRLO_tdcTime                  ;     
   double T_coin_pPRLO_tdcTimeRaw               ;     
   double T_coin_pPSHWR_adcMultiplicity         ;     
   double T_coin_pPSHWR_adcPed                  ;     
   double T_coin_pPSHWR_adcPedRaw               ;     
   double T_coin_pPSHWR_adcPulseAmp             ;     
   double T_coin_pPSHWR_adcPulseAmpRaw          ;     
   double T_coin_pPSHWR_adcPulseInt             ;     
   double T_coin_pPSHWR_adcPulseIntRaw          ;     
   double T_coin_pPSHWR_adcPulseTime            ;     
   double T_coin_pPSHWR_adcPulseTimeRaw         ;     
   double T_coin_pRF_tdcMultiplicity            ;     
   double T_coin_pRF_tdcTime                    ;     
   double T_coin_pRF_tdcTimeRaw                 ;     
   double T_coin_pSTOF_ROC1_tdcMultiplicity     ;     
   double T_coin_pSTOF_ROC1_tdcTime             ;     
   double T_coin_pSTOF_ROC1_tdcTimeRaw          ;     
   double T_coin_pSTOF_ROC2_tdcMultiplicity     ;     
   double T_coin_pSTOF_ROC2_tdcTime             ;     
   double T_coin_pSTOF_ROC2_tdcTimeRaw          ;     
   double T_coin_pT1_tdcMultiplicity            ;     
   double T_coin_pT1_tdcTime                    ;     
   double T_coin_pT1_tdcTimeRaw                 ;     
   double T_coin_pT2_tdcMultiplicity            ;     
   double T_coin_pT2_tdcTime                    ;     
   double T_coin_pT2_tdcTimeRaw                 ;     
   double T_coin_pT3_tdcMultiplicity            ;     
   double T_coin_pT3_tdcTime                    ;     
   double T_coin_pT3_tdcTimeRaw                 ;     
   double T_coin_pTRIG1_ROC1_tdcMultiplicity    ;     
   double T_coin_pTRIG1_ROC1_tdcTime            ;     
   double T_coin_pTRIG1_ROC1_tdcTimeRaw         ;     
   double T_coin_pTRIG1_ROC2_tdcMultiplicity    ;     
   double T_coin_pTRIG1_ROC2_tdcTime            ;     
   double T_coin_pTRIG1_ROC2_tdcTimeRaw         ;     
   double T_coin_pTRIG2_ROC1_tdcMultiplicity    ;     
   double T_coin_pTRIG2_ROC1_tdcTime            ;    
   double T_coin_pTRIG2_ROC1_tdcTimeRaw         ;    
   double T_coin_pTRIG2_ROC2_tdcMultiplicity    ;    
   double T_coin_pTRIG2_ROC2_tdcTime            ;    
   double T_coin_pTRIG2_ROC2_tdcTimeRaw         ;    
   double T_coin_pTRIG3_ROC1_tdcMultiplicity    ;    
   double T_coin_pTRIG3_ROC1_tdcTime            ;    
   double T_coin_pTRIG3_ROC1_tdcTimeRaw         ;    
   double T_coin_pTRIG3_ROC2_tdcMultiplicity    ;    
   double T_coin_pTRIG3_ROC2_tdcTime            ;    
   double T_coin_pTRIG3_ROC2_tdcTimeRaw         ;    
   double T_coin_pTRIG4_ROC1_tdcMultiplicity    ;    
   double T_coin_pTRIG4_ROC1_tdcTime            ;    
   double T_coin_pTRIG4_ROC1_tdcTimeRaw         ;    
   double T_coin_pTRIG4_ROC2_tdcMultiplicity    ;    
   double T_coin_pTRIG4_ROC2_tdcTime            ;    
   double T_coin_pTRIG4_ROC2_tdcTimeRaw         ;    
   double T_coin_pTRIG5_ROC1_tdcMultiplicity    ;    
   double T_coin_pTRIG5_ROC1_tdcTime            ;    
   double T_coin_pTRIG5_ROC1_tdcTimeRaw         ;    
   double T_coin_pTRIG5_ROC2_tdcMultiplicity    ;    
   double T_coin_pTRIG5_ROC2_tdcTime            ;    
   double T_coin_pTRIG5_ROC2_tdcTimeRaw         ;    
   double T_coin_pTRIG6_ROC1_tdcMultiplicity    ;    
   double T_coin_pTRIG6_ROC1_tdcTime            ;    
   double T_coin_pTRIG6_ROC1_tdcTimeRaw         ;    
   double T_coin_pTRIG6_ROC2_tdcMultiplicity    ;    
   double T_coin_pTRIG6_ROC2_tdcTime            ;   
   double T_coin_pTRIG6_ROC2_tdcTimeRaw         ;   
   int g_evtyp                               ;   
   double IPM3H07A_XPOS                         ;   
   double IPM3H07A_YPOS                         ;   
   double IPM3H07B_XPOS                         ;   
   double IPM3H07B_YPOS                         ;   
   double IPM3H07C_XPOS                         ;   
   double IPM3H07C_YPOS                         ;   
   double IPM3H07A_XRAW                         ;   
   double IPM3H07A_YRAW                         ;   
   double IPM3H07B_XRAW                         ;   
   double IPM3H07B_YRAW                         ;   
   double IPM3H07C_XRAW                         ;   
   double IPM3H07C_YRAW                         ;   
   double IPM3H07A_XSOF                         ;   
   double IPM3H07A_YSOF                         ;   
   double IPM3H07B_XSOF                         ;   
   double IPM3H07B_YSOF                         ;   
   double IPM3H07C_XSOF                         ;   
   double IPM3H07C_YSOF                         ;   
   ULong64_t fEvtHdr_fEvtTime                      ; 
   UInt_t fEvtHdr_fEvtNum                       ;  
   int fEvtHdr_fEvtType                      ;  
   int fEvtHdr_fEvtLen                       ;  
   int fEvtHdr_fHelicity                     ;  
   int fEvtHdr_fTargetPol                    ;  
   int fEvtHdr_fRun                          ;  
   double IBC3H00CRCUR4                         ;   
   double IGL1I00OD16_16                        ;   
   double HELFREQ                               ;   
   double HELDELAYs                             ;   
   double hac_bcm_average                       ;   
   double ibcm1                                 ;   
   double ibcm2                                 ;   
   double iunser                                ;   
   double itov3out                              ;   
   double itov4out                              ;   
   //int Event_Branch                          ;   


   TBranch *b_H_gtr_xptar                ;
   TBranch *b_H_gtr_yptar                ;
   TBranch *b_P_gtr_xptar                ;
   TBranch *b_P_gtr_yptar                ;
   TBranch *b_mmiss                      ;
   TBranch *b_CTime_epCoinTime_ROC1      ;                     
   TBranch *b_CTime_epCoinTime_ROC2      ;                     
   TBranch *b_CTime_epCoinTime_TRIG1     ;                     
   TBranch *b_CTime_epCoinTime_TRIG4     ;                     
   TBranch *b_H_cal_eprtrack             ;                
   TBranch *b_H_cal_eprtracknorm         ;                
   TBranch *b_H_cal_etot                 ;                
   TBranch *b_H_cal_etotnorm             ;                
   TBranch *b_H_cal_etottracknorm        ;                
   TBranch *b_H_cal_etrack               ;                
   TBranch *b_H_cal_etracknorm           ;                
   TBranch *b_H_cer_npeSum               ;                
   TBranch *b_H_dc_ntrack                ;                
   TBranch *b_H_dc_x_fp                  ;                
   TBranch *b_H_dc_xp_fp                 ;                
   TBranch *b_H_dc_y_fp                  ;                
   TBranch *b_H_dc_yp_fp                 ;                
   TBranch *b_H_extcor_xsieve            ;                
   TBranch *b_H_extcor_ysieve            ;                
   TBranch *b_H_gtr_beta                 ;                
   TBranch *b_H_gtr_dp                   ;                
   TBranch *b_H_gtr_index                ;                
   TBranch *b_H_gtr_ok                   ;                
   TBranch *b_H_gtr_p                    ;                
   TBranch *b_H_gtr_ph                   ;                
   TBranch *b_H_gtr_px                   ;                
   TBranch *b_H_gtr_py                   ;                
   TBranch *b_H_gtr_pz                   ;                
   TBranch *b_H_gtr_th                   ;                
   TBranch *b_H_gtr_x                    ;                
   TBranch *b_H_gtr_y                    ;                
   TBranch *b_H_hod_beta                 ;                
   TBranch *b_H_hod_betachisqnotrack     ;               
   TBranch *b_H_hod_betanotrack          ;               
   TBranch *b_H_hod_fpHitsTime           ;               
   TBranch *b_H_hod_starttime            ;               
   TBranch *b_H_kin_primary_Q2           ;               
   TBranch *b_H_kin_primary_W            ;               
   TBranch *b_H_kin_primary_W2           ;               
   TBranch *b_H_kin_primary_epsilon      ;               
   TBranch *b_H_kin_primary_nu           ;               
   TBranch *b_H_kin_primary_omega        ;               
   TBranch *b_H_kin_primary_ph_q         ;               
   TBranch *b_H_kin_primary_q3m          ;               
   TBranch *b_H_kin_primary_q_x          ;               
   TBranch *b_H_kin_primary_q_y          ;               
   TBranch *b_H_kin_primary_q_z          ;              
   TBranch *b_H_kin_primary_scat_ang_deg ;               
   TBranch *b_H_kin_primary_scat_ang_rad ;              
   TBranch *b_H_kin_primary_th_q         ;             
   TBranch *b_H_kin_primary_x_bj         ;            
   TBranch *b_H_rb_raster_fr_xbpm_tar    ;              
   TBranch *b_H_rb_raster_fr_ybpm_tar    ;              
   TBranch *b_H_react_x                  ;           
   TBranch *b_H_react_y                  ;           
   TBranch *b_H_react_z                  ;           
   TBranch *b_P_aero_npeSum              ;          
   TBranch *b_P_cal_eprtrack             ;          
   TBranch *b_P_cal_eprtracknorm         ;          
   TBranch *b_P_cal_etot                 ;          
   TBranch *b_P_cal_etotnorm             ;          
   TBranch *b_P_cal_etottracknorm        ;          
   TBranch *b_P_cal_etracknorm           ;          
   TBranch *b_P_cal_pr_eplane            ;          
   TBranch *b_P_dc_ntrack                ;          
   TBranch *b_P_dc_x_fp                  ;          
   TBranch *b_P_dc_xp_fp                 ;          
   TBranch *b_P_dc_y_fp                  ;          
   TBranch *b_P_dc_yp_fp                 ;          
   TBranch *b_P_extcor_xsieve            ;          
   TBranch *b_P_extcor_ysieve            ;          
   TBranch *b_P_gtr_beta                 ;          
   TBranch *b_P_gtr_dp                   ;          
   TBranch *b_P_gtr_index                ;         
   TBranch *b_P_gtr_ok                   ;         
   TBranch *b_P_gtr_p                    ;         
   TBranch *b_P_gtr_ph                   ;         
   TBranch *b_P_gtr_px                   ;         
   TBranch *b_P_gtr_py                   ;         
   TBranch *b_P_gtr_pz                   ;         
   TBranch *b_P_gtr_th                   ;         
   TBranch *b_P_gtr_x                    ;         
   TBranch *b_P_gtr_y                    ;         
   TBranch *b_P_hgcer_npeSum             ;         
   TBranch *b_P_hod_beta                 ;         
   TBranch *b_P_hod_betachisqnotrack     ;         
   TBranch *b_P_hod_betanotrack          ;        
   TBranch *b_P_hod_fpHitsTime           ;        
   TBranch *b_P_hod_goodscinhit          ;        
   TBranch *b_P_hod_starttime            ;        
   TBranch *b_P_kin_secondary_Erecoil    ;        
   TBranch *b_P_kin_secondary_MandelS    ;        
   TBranch *b_P_kin_secondary_MandelT    ;        
   TBranch *b_P_kin_secondary_MandelU    ;        
   TBranch *b_P_kin_secondary_Mrecoil    ;        
   TBranch *b_P_kin_secondary_Prec_x     ;        
   TBranch *b_P_kin_secondary_Prec_y     ;        
   TBranch *b_P_kin_secondary_Prec_z     ;        
   TBranch *b_P_kin_secondary_emiss      ;        
   TBranch *b_P_kin_secondary_emiss_nuc  ;        
   TBranch *b_P_kin_secondary_ph_bq      ;              
   TBranch *b_P_kin_secondary_ph_xq      ;              
   TBranch *b_P_kin_secondary_phb_cm     ;              
   TBranch *b_P_kin_secondary_phx_cm     ;              
   TBranch *b_P_kin_secondary_pmiss      ;              
   TBranch *b_P_kin_secondary_pmiss_x    ;              
   TBranch *b_P_kin_secondary_pmiss_y    ;              
   TBranch *b_P_kin_secondary_pmiss_z    ;              
   TBranch *b_P_kin_secondary_px_cm      ;              
   TBranch *b_P_kin_secondary_t_tot_cm   ;              
   TBranch *b_P_kin_secondary_tb         ;              
   TBranch *b_P_kin_secondary_tb_cm      ;              
   TBranch *b_P_kin_secondary_th_bq      ;              
   TBranch *b_P_kin_secondary_th_xq      ;              
   TBranch *b_P_kin_secondary_thb_cm     ;              
   TBranch *b_P_kin_secondary_thx_cm     ;              
   TBranch *b_P_kin_secondary_tx         ;              
   TBranch *b_P_kin_secondary_tx_cm      ;              
   TBranch *b_P_kin_secondary_xangle     ;              
   TBranch *b_P_ngcer_npeSum             ;              
   TBranch *b_P_react_z                  ;              
   TBranch *b_T_coin_h1T_tdcMultiplicity ;              
   TBranch *b_T_coin_h1T_tdcTime         ;              
   TBranch *b_T_coin_h1T_tdcTimeRaw      ;              
   TBranch *b_T_coin_h1X_tdcMultiplicity ;              
   TBranch *b_T_coin_h1X_tdcTime         ;              
   TBranch *b_T_coin_h1X_tdcTimeRaw      ;              
   TBranch *b_T_coin_h1Y_tdcMultiplicity ;              
   TBranch *b_T_coin_h1Y_tdcTime         ;              
   TBranch *b_T_coin_h1Y_tdcTimeRaw      ;              
   TBranch *b_T_coin_h2T_tdcMultiplicity ;              
   TBranch *b_T_coin_h2T_tdcTime         ;              
   TBranch *b_T_coin_h2T_tdcTimeRaw      ;              
   TBranch *b_T_coin_h2X_tdcMultiplicity ;              
   TBranch *b_T_coin_h2X_tdcTime         ;              
   TBranch *b_T_coin_h2X_tdcTimeRaw      ;              
   TBranch *b_T_coin_h2Y_tdcMultiplicity ;              
   TBranch *b_T_coin_h2Y_tdcTime         ;              
   TBranch *b_T_coin_h2Y_tdcTimeRaw      ;              
   TBranch *b_T_coin_hAER_adcMultiplicity;              
   TBranch *b_T_coin_hAER_adcPed         ;             
   TBranch *b_T_coin_hAER_adcPedRaw      ;             
   TBranch *b_T_coin_hAER_adcPulseAmp    ;             
   TBranch *b_T_coin_hAER_adcPulseAmpRaw ;             
   TBranch *b_T_coin_hAER_adcPulseInt    ;             
   TBranch *b_T_coin_hAER_adcPulseIntRaw ;             
   TBranch *b_T_coin_hAER_adcPulseTime   ;             
   TBranch *b_T_coin_hAER_adcPulseTimeRaw;             
   TBranch *b_T_coin_hASUM_adcMultiplicity;            
   TBranch *b_T_coin_hASUM_adcPed         ;            
   TBranch *b_T_coin_hASUM_adcPedRaw      ;            
   TBranch *b_T_coin_hASUM_adcPulseAmp    ;            
   TBranch *b_T_coin_hASUM_adcPulseAmpRaw ;            
   TBranch *b_T_coin_hASUM_adcPulseInt    ;            
   TBranch *b_T_coin_hASUM_adcPulseIntRaw ;            
   TBranch *b_T_coin_hASUM_adcPulseTime   ;            
   TBranch *b_T_coin_hASUM_adcPulseTimeRaw;            
   TBranch *b_T_coin_hASUM_tdcMultiplicity;            
   TBranch *b_T_coin_hASUM_tdcTime        ;            
   TBranch *b_T_coin_hASUM_tdcTimeRaw     ;            
   TBranch *b_T_coin_hBSUM_adcMultiplicity;            
   TBranch *b_T_coin_hBSUM_adcPed         ;           
   TBranch *b_T_coin_hBSUM_adcPedRaw      ;           
   TBranch *b_T_coin_hBSUM_adcPulseAmp    ;           
   TBranch *b_T_coin_hBSUM_adcPulseAmpRaw ;           
   TBranch *b_T_coin_hBSUM_adcPulseInt    ;           
   TBranch *b_T_coin_hBSUM_adcPulseIntRaw ;           
   TBranch *b_T_coin_hBSUM_adcPulseTime   ;           
   TBranch *b_T_coin_hBSUM_adcPulseTimeRaw;           
   TBranch *b_T_coin_hBSUM_tdcMultiplicity;           
   TBranch *b_T_coin_hBSUM_tdcTime        ;           
   TBranch *b_T_coin_hBSUM_tdcTimeRaw     ;           
   TBranch *b_T_coin_hCER_adcMultiplicity ;           
   TBranch *b_T_coin_hCER_adcPed          ;           
   TBranch *b_T_coin_hCER_adcPedRaw       ;           
   TBranch *b_T_coin_hCER_adcPulseAmp     ;           
   TBranch *b_T_coin_hCER_adcPulseAmpRaw  ;           
   TBranch *b_T_coin_hCER_adcPulseInt     ;           
   TBranch *b_T_coin_hCER_adcPulseIntRaw  ;           
   TBranch *b_T_coin_hCER_adcPulseTime    ;           
   TBranch *b_T_coin_hCER_adcPulseTimeRaw ;           
   TBranch *b_T_coin_hCER_tdcMultiplicity ;          
   TBranch *b_T_coin_hCER_tdcTime         ;          
   TBranch *b_T_coin_hCER_tdcTimeRaw      ;          
   TBranch *b_T_coin_hCSUM_adcMultiplicity;          
   TBranch *b_T_coin_hCSUM_adcPed         ;          
   TBranch *b_T_coin_hCSUM_adcPedRaw      ;          
   TBranch *b_T_coin_hCSUM_adcPulseAmp    ;          
   TBranch *b_T_coin_hCSUM_adcPulseAmpRaw ;          
   TBranch *b_T_coin_hCSUM_adcPulseInt    ;          
   TBranch *b_T_coin_hCSUM_adcPulseIntRaw ;          
   TBranch *b_T_coin_hCSUM_adcPulseTime   ;          
   TBranch *b_T_coin_hCSUM_adcPulseTimeRaw;          
   TBranch *b_T_coin_hCSUM_tdcMultiplicity;          
   TBranch *b_T_coin_hCSUM_tdcTime        ;          
   TBranch *b_T_coin_hCSUM_tdcTimeRaw     ;          
   TBranch *b_T_coin_hDCREF1_tdcMultiplicity;         
   TBranch *b_T_coin_hDCREF1_tdcTime        ;         
   TBranch *b_T_coin_hDCREF1_tdcTimeRaw     ;         
   TBranch *b_T_coin_hDCREF2_tdcMultiplicity;         
   TBranch *b_T_coin_hDCREF2_tdcTime        ;         
   TBranch *b_T_coin_hDCREF2_tdcTimeRaw     ;         
   TBranch *b_T_coin_hDCREF3_tdcMultiplicity;         
   TBranch *b_T_coin_hDCREF3_tdcTime        ;         
   TBranch *b_T_coin_hDCREF3_tdcTimeRaw     ;         
   TBranch *b_T_coin_hDCREF4_tdcMultiplicity;         
   TBranch *b_T_coin_hDCREF4_tdcTime        ;         
   TBranch *b_T_coin_hDCREF4_tdcTimeRaw     ;         
   TBranch *b_T_coin_hDCREF5_tdcMultiplicity;         
   TBranch *b_T_coin_hDCREF5_tdcTime        ;        
   TBranch *b_T_coin_hDCREF5_tdcTimeRaw     ;        
   TBranch *b_T_coin_hDSUM_adcMultiplicity  ;        
   TBranch *b_T_coin_hDSUM_adcPed           ;        
   TBranch *b_T_coin_hDSUM_adcPedRaw        ;        
   TBranch *b_T_coin_hDSUM_adcPulseAmp      ;        
   TBranch *b_T_coin_hDSUM_adcPulseAmpRaw   ;        
   TBranch *b_T_coin_hDSUM_adcPulseInt      ;        
   TBranch *b_T_coin_hDSUM_adcPulseIntRaw   ;        
   TBranch *b_T_coin_hDSUM_adcPulseTime     ;        
   TBranch *b_T_coin_hDSUM_adcPulseTimeRaw  ;        
   TBranch *b_T_coin_hDSUM_tdcMultiplicity  ;        
   TBranch *b_T_coin_hDSUM_tdcTime          ;        
   TBranch *b_T_coin_hDSUM_tdcTimeRaw       ;        
   TBranch *b_T_coin_hEDTM_tdcMultiplicity  ;        
   TBranch *b_T_coin_hEDTM_tdcTime          ;        
   TBranch *b_T_coin_hEDTM_tdcTimeRaw       ;        
   TBranch *b_T_coin_hEL_CLEAN_ROC1_tdcMultiplicity ;
   TBranch *b_T_coin_hEL_CLEAN_ROC1_tdcTime         ;
   TBranch *b_T_coin_hEL_CLEAN_ROC1_tdcTimeRaw      ;
   TBranch *b_T_coin_hEL_CLEAN_ROC2_tdcMultiplicity ;
   TBranch *b_T_coin_hEL_CLEAN_ROC2_tdcTime         ;
   TBranch *b_T_coin_hEL_CLEAN_ROC2_tdcTimeRaw      ;
   TBranch *b_T_coin_hEL_HI_ROC1_tdcMultiplicity    ;
   TBranch *b_T_coin_hEL_HI_ROC1_tdcTime            ;
   TBranch *b_T_coin_hEL_HI_ROC1_tdcTimeRaw         ;
   TBranch *b_T_coin_hEL_HI_ROC2_tdcMultiplicity    ;
   TBranch *b_T_coin_hEL_HI_ROC2_tdcTime            ;
   TBranch *b_T_coin_hEL_HI_ROC2_tdcTimeRaw         ;
   TBranch *b_T_coin_hEL_LO_LO_ROC1_tdcMultiplicity ;
   TBranch *b_T_coin_hEL_LO_LO_ROC1_tdcTime         ;
   TBranch *b_T_coin_hEL_LO_LO_ROC1_tdcTimeRaw      ;
   TBranch *b_T_coin_hEL_LO_LO_ROC2_tdcMultiplicity ;
   TBranch *b_T_coin_hEL_LO_LO_ROC2_tdcTime         ;
   TBranch *b_T_coin_hEL_LO_LO_ROC2_tdcTimeRaw      ;
   TBranch *b_T_coin_hEL_LO_ROC1_tdcMultiplicity    ;
   TBranch *b_T_coin_hEL_LO_ROC1_tdcTime            ;
   TBranch *b_T_coin_hEL_LO_ROC1_tdcTimeRaw         ;
   TBranch *b_T_coin_hEL_LO_ROC2_tdcMultiplicity    ;
   TBranch *b_T_coin_hEL_LO_ROC2_tdcTime            ;
   TBranch *b_T_coin_hEL_LO_ROC2_tdcTimeRaw         ;
   TBranch *b_T_coin_hEL_REAL_ROC1_tdcMultiplicity  ;
   TBranch *b_T_coin_hEL_REAL_ROC1_tdcTime          ;   
   TBranch *b_T_coin_hEL_REAL_ROC1_tdcTimeRaw       ;   
   TBranch *b_T_coin_hEL_REAL_ROC2_tdcMultiplicity  ;   
   TBranch *b_T_coin_hEL_REAL_ROC2_tdcTime          ;   
   TBranch *b_T_coin_hEL_REAL_ROC2_tdcTimeRaw       ;   
   TBranch *b_T_coin_hFADC_TREF_ROC1_adcMultiplicity;   
   TBranch *b_T_coin_hFADC_TREF_ROC1_adcPed         ;   
   TBranch *b_T_coin_hFADC_TREF_ROC1_adcPedRaw      ;   
   TBranch *b_T_coin_hFADC_TREF_ROC1_adcPulseAmp    ;   
   TBranch *b_T_coin_hFADC_TREF_ROC1_adcPulseAmpRaw ;   
   TBranch *b_T_coin_hFADC_TREF_ROC1_adcPulseInt    ;   
   TBranch *b_T_coin_hFADC_TREF_ROC1_adcPulseIntRaw ;   
   TBranch *b_T_coin_hFADC_TREF_ROC1_adcPulseTime   ;   
   TBranch *b_T_coin_hFADC_TREF_ROC1_adcPulseTimeRaw;   
   TBranch *b_T_coin_hHODO_RF_tdcMultiplicity       ;   
   TBranch *b_T_coin_hHODO_RF_tdcTime               ;   
   TBranch *b_T_coin_hHODO_RF_tdcTimeRaw            ;   
   TBranch *b_T_coin_hPRE100_ROC1_tdcMultiplicity   ;   
   TBranch *b_T_coin_hPRE100_ROC1_tdcTime           ;   
   TBranch *b_T_coin_hPRE100_ROC1_tdcTimeRaw        ;   
   TBranch *b_T_coin_hPRE100_ROC2_tdcMultiplicity   ;   
   TBranch *b_T_coin_hPRE100_ROC2_tdcTime           ;   
   TBranch *b_T_coin_hPRE100_ROC2_tdcTimeRaw        ;   
   TBranch *b_T_coin_hPRE150_ROC1_tdcMultiplicity   ;   
   TBranch *b_T_coin_hPRE150_ROC1_tdcTime           ;   
   TBranch *b_T_coin_hPRE150_ROC1_tdcTimeRaw        ;   
   TBranch *b_T_coin_hPRE150_ROC2_tdcMultiplicity   ;   
   TBranch *b_T_coin_hPRE150_ROC2_tdcTime           ;   
   TBranch *b_T_coin_hPRE150_ROC2_tdcTimeRaw        ;   
   TBranch *b_T_coin_hPRE200_ROC1_tdcMultiplicity   ;   
   TBranch *b_T_coin_hPRE200_ROC1_tdcTime           ;   
   TBranch *b_T_coin_hPRE200_ROC1_tdcTimeRaw        ;   
   TBranch *b_T_coin_hPRE200_ROC2_tdcMultiplicity   ;   
   TBranch *b_T_coin_hPRE200_ROC2_tdcTime           ;   
   TBranch *b_T_coin_hPRE200_ROC2_tdcTimeRaw        ;   
   TBranch *b_T_coin_hPRE40_ROC1_tdcMultiplicity    ;   
   TBranch *b_T_coin_hPRE40_ROC1_tdcTime            ;  
   TBranch *b_T_coin_hPRE40_ROC1_tdcTimeRaw         ;  
   TBranch *b_T_coin_hPRE40_ROC2_tdcMultiplicity    ;  
   TBranch *b_T_coin_hPRE40_ROC2_tdcTime            ;  
   TBranch *b_T_coin_hPRE40_ROC2_tdcTimeRaw         ;  
   TBranch *b_T_coin_hPRHI_tdcMultiplicity          ;  
   TBranch *b_T_coin_hPRHI_tdcTime                  ;  
   TBranch *b_T_coin_hPRHI_tdcTimeRaw               ;  
   TBranch *b_T_coin_hPRLO_tdcMultiplicity          ;  
   TBranch *b_T_coin_hPRLO_tdcTime                  ;  
   TBranch *b_T_coin_hPRLO_tdcTimeRaw               ;  
   TBranch *b_T_coin_hPSHWR_adcMultiplicity         ;  
   TBranch *b_T_coin_hPSHWR_adcPed                  ;  
   TBranch *b_T_coin_hPSHWR_adcPedRaw               ;  
   TBranch *b_T_coin_hPSHWR_adcPulseAmp             ;  
   TBranch *b_T_coin_hPSHWR_adcPulseAmpRaw          ;  
   TBranch *b_T_coin_hPSHWR_adcPulseInt             ;  
   TBranch *b_T_coin_hPSHWR_adcPulseIntRaw          ;  
   TBranch *b_T_coin_hPSHWR_adcPulseTime            ;  
   TBranch *b_T_coin_hPSHWR_adcPulseTimeRaw         ;  
   TBranch *b_T_coin_hRF_tdcMultiplicity            ;  
   TBranch *b_T_coin_hRF_tdcTime                    ;  
   TBranch *b_T_coin_hRF_tdcTimeRaw                 ;  
   TBranch *b_T_coin_hSHWR_adcMultiplicity          ;  
   TBranch *b_T_coin_hSHWR_adcPed                   ;  
   TBranch *b_T_coin_hSHWR_adcPedRaw                ;  
   TBranch *b_T_coin_hSHWR_adcPulseAmp              ;  
   TBranch *b_T_coin_hSHWR_adcPulseAmpRaw           ;  
   TBranch *b_T_coin_hSHWR_adcPulseInt              ;  
   TBranch *b_T_coin_hSHWR_adcPulseIntRaw           ;  
   TBranch *b_T_coin_hSHWR_adcPulseTime             ;  
   TBranch *b_T_coin_hSHWR_adcPulseTimeRaw          ;  
   TBranch *b_T_coin_hSHWR_tdcMultiplicity          ;  
   TBranch *b_T_coin_hSHWR_tdcTime                  ;  
   TBranch *b_T_coin_hSHWR_tdcTimeRaw               ;  
   TBranch *b_T_coin_hSTOF_ROC1_tdcMultiplicity     ;  
   TBranch *b_T_coin_hSTOF_ROC1_tdcTime             ;  
   TBranch *b_T_coin_hSTOF_ROC1_tdcTimeRaw          ;  
   TBranch *b_T_coin_hSTOF_ROC2_tdcMultiplicity     ;  
   TBranch *b_T_coin_hSTOF_ROC2_tdcTime             ; 
   TBranch *b_T_coin_hSTOF_ROC2_tdcTimeRaw          ; 
   TBranch *b_T_coin_hT1_tdcMultiplicity            ; 
   TBranch *b_T_coin_hT1_tdcTime                    ; 
   TBranch *b_T_coin_hT1_tdcTimeRaw                 ; 
   TBranch *b_T_coin_hT2_tdcMultiplicity            ; 
   TBranch *b_T_coin_hT2_tdcTime                    ; 
   TBranch *b_T_coin_hT2_tdcTimeRaw                 ; 
   TBranch *b_T_coin_hTRIG1_ROC1_tdcMultiplicity    ; 
   TBranch *b_T_coin_hTRIG1_ROC1_tdcTime            ; 
   TBranch *b_T_coin_hTRIG1_ROC1_tdcTimeRaw         ; 
   TBranch *b_T_coin_hTRIG1_ROC2_tdcMultiplicity    ; 
   TBranch *b_T_coin_hTRIG1_ROC2_tdcTime            ; 
   TBranch *b_T_coin_hTRIG1_ROC2_tdcTimeRaw         ; 
   TBranch *b_T_coin_hTRIG2_ROC1_tdcMultiplicity    ; 
   TBranch *b_T_coin_hTRIG2_ROC1_tdcTime            ; 
   TBranch *b_T_coin_hTRIG2_ROC1_tdcTimeRaw         ; 
   TBranch *b_T_coin_hTRIG2_ROC2_tdcMultiplicity    ; 
   TBranch *b_T_coin_hTRIG2_ROC2_tdcTime            ; 
   TBranch *b_T_coin_hTRIG2_ROC2_tdcTimeRaw         ; 
   TBranch *b_T_coin_hTRIG3_ROC1_tdcMultiplicity    ; 
   TBranch *b_T_coin_hTRIG3_ROC1_tdcTime            ; 
   TBranch *b_T_coin_hTRIG3_ROC1_tdcTimeRaw         ; 
   TBranch *b_T_coin_hTRIG3_ROC2_tdcMultiplicity    ; 
   TBranch *b_T_coin_hTRIG3_ROC2_tdcTime            ; 
   TBranch *b_T_coin_hTRIG3_ROC2_tdcTimeRaw         ; 
   TBranch *b_T_coin_hTRIG4_ROC1_tdcMultiplicity    ; 
   TBranch *b_T_coin_hTRIG4_ROC1_tdcTime            ; 
   TBranch *b_T_coin_hTRIG4_ROC1_tdcTimeRaw         ; 
   TBranch *b_T_coin_hTRIG4_ROC2_tdcMultiplicity    ; 
   TBranch *b_T_coin_hTRIG4_ROC2_tdcTime            ; 
   TBranch *b_T_coin_hTRIG4_ROC2_tdcTimeRaw         ; 
   TBranch *b_T_coin_hTRIG5_ROC1_tdcMultiplicity    ; 
   TBranch *b_T_coin_hTRIG5_ROC1_tdcTime            ; 
   TBranch *b_T_coin_hTRIG5_ROC1_tdcTimeRaw         ; 
   TBranch *b_T_coin_hTRIG5_ROC2_tdcMultiplicity    ; 
   TBranch *b_T_coin_hTRIG5_ROC2_tdcTime            ; 
   TBranch *b_T_coin_hTRIG5_ROC2_tdcTimeRaw         ; 
   TBranch *b_T_coin_hTRIG6_ROC1_tdcMultiplicity    ; 
   TBranch *b_T_coin_hTRIG6_ROC1_tdcTime            ; 
   TBranch *b_T_coin_hTRIG6_ROC1_tdcTimeRaw         ; 
   TBranch *b_T_coin_hTRIG6_ROC2_tdcMultiplicity    ; 
   TBranch *b_T_coin_hTRIG6_ROC2_tdcTime            ;
   TBranch *b_T_coin_hTRIG6_ROC2_tdcTimeRaw         ;
   TBranch *b_T_coin_p1T_tdcMultiplicity            ;
   TBranch *b_T_coin_p1T_tdcTime                    ;
   TBranch *b_T_coin_p1T_tdcTimeRaw                 ;
   TBranch *b_T_coin_p1X_tdcMultiplicity            ;
   TBranch *b_T_coin_p1X_tdcTime                    ;
   TBranch *b_T_coin_p1X_tdcTimeRaw                 ;
   TBranch *b_T_coin_p1Y_tdcMultiplicity            ;
   TBranch *b_T_coin_p1Y_tdcTime                    ;
   TBranch *b_T_coin_p1Y_tdcTimeRaw                 ;
   TBranch *b_T_coin_p2T_tdcMultiplicity            ;
   TBranch *b_T_coin_p2T_tdcTime                    ;
   TBranch *b_T_coin_p2T_tdcTimeRaw                 ;
   TBranch *b_T_coin_p2X_tdcMultiplicity            ;
   TBranch *b_T_coin_p2X_tdcTime                    ;
   TBranch *b_T_coin_p2X_tdcTimeRaw                 ;
   TBranch *b_T_coin_p2Y_tdcMultiplicity            ;
   TBranch *b_T_coin_p2Y_tdcTime                    ;
   TBranch *b_T_coin_p2Y_tdcTimeRaw                 ;
   TBranch *b_T_coin_pAER_adcMultiplicity           ;
   TBranch *b_T_coin_pAER_adcPed                    ;
   TBranch *b_T_coin_pAER_adcPedRaw                 ;
   TBranch *b_T_coin_pAER_adcPulseAmp               ;
   TBranch *b_T_coin_pAER_adcPulseAmpRaw            ;
   TBranch *b_T_coin_pAER_adcPulseInt               ;
   TBranch *b_T_coin_pAER_adcPulseIntRaw            ;
   TBranch *b_T_coin_pAER_adcPulseTime              ;
   TBranch *b_T_coin_pAER_adcPulseTimeRaw           ;
   TBranch *b_T_coin_pAER_tdcMultiplicity           ;
   TBranch *b_T_coin_pAER_tdcTime                   ;
   TBranch *b_T_coin_pAER_tdcTimeRaw                ;
   TBranch *b_T_coin_pDCREF10_tdcMultiplicity       ;
   TBranch *b_T_coin_pDCREF10_tdcTime               ;
   TBranch *b_T_coin_pDCREF10_tdcTimeRaw            ;
   TBranch *b_T_coin_pDCREF1_tdcMultiplicity        ;
   TBranch *b_T_coin_pDCREF1_tdcTime                ;
   TBranch *b_T_coin_pDCREF1_tdcTimeRaw             ;
   TBranch *b_T_coin_pDCREF2_tdcMultiplicity        ;
   TBranch *b_T_coin_pDCREF2_tdcTime                ;
   TBranch *b_T_coin_pDCREF2_tdcTimeRaw             ;
   TBranch *b_T_coin_pDCREF3_tdcMultiplicity        ;
   TBranch *b_T_coin_pDCREF3_tdcTime                ;
   TBranch *b_T_coin_pDCREF3_tdcTimeRaw             ;
   TBranch *b_T_coin_pDCREF4_tdcMultiplicity        ;
   TBranch *b_T_coin_pDCREF4_tdcTime                ;
   TBranch *b_T_coin_pDCREF4_tdcTimeRaw             ;
   TBranch *b_T_coin_pDCREF5_tdcMultiplicity        ;
   TBranch *b_T_coin_pDCREF5_tdcTime                ;
   TBranch *b_T_coin_pDCREF5_tdcTimeRaw             ;
   TBranch *b_T_coin_pDCREF6_tdcMultiplicity        ;
   TBranch *b_T_coin_pDCREF6_tdcTime                ;
   TBranch *b_T_coin_pDCREF6_tdcTimeRaw             ;
   TBranch *b_T_coin_pDCREF7_tdcMultiplicity        ;
   TBranch *b_T_coin_pDCREF7_tdcTime                ;
   TBranch *b_T_coin_pDCREF7_tdcTimeRaw             ;
   TBranch *b_T_coin_pDCREF8_tdcMultiplicity        ;
   TBranch *b_T_coin_pDCREF8_tdcTime                ;
   TBranch *b_T_coin_pDCREF8_tdcTimeRaw             ;
   TBranch *b_T_coin_pDCREF9_tdcMultiplicity        ;
   TBranch *b_T_coin_pDCREF9_tdcTime                ;
   TBranch *b_T_coin_pDCREF9_tdcTimeRaw             ;
   TBranch *b_T_coin_pEDTM_tdcMultiplicity          ;
   TBranch *b_T_coin_pEDTM_tdcTime                  ;
   TBranch *b_T_coin_pEDTM_tdcTimeRaw               ;
   TBranch *b_T_coin_pEL_CLEAN_ROC1_tdcMultiplicity ;
   TBranch *b_T_coin_pEL_CLEAN_ROC1_tdcTime         ;        
   TBranch *b_T_coin_pEL_CLEAN_ROC1_tdcTimeRaw      ;        
   TBranch *b_T_coin_pEL_CLEAN_ROC2_tdcMultiplicity ;        
   TBranch *b_T_coin_pEL_CLEAN_ROC2_tdcTime         ;        
   TBranch *b_T_coin_pEL_CLEAN_ROC2_tdcTimeRaw      ;        
   TBranch *b_T_coin_pEL_HI_ROC1_tdcMultiplicity    ;        
   TBranch *b_T_coin_pEL_HI_ROC1_tdcTime            ;        
   TBranch *b_T_coin_pEL_HI_ROC1_tdcTimeRaw         ;        
   TBranch *b_T_coin_pEL_HI_ROC2_tdcMultiplicity    ;        
   TBranch *b_T_coin_pEL_HI_ROC2_tdcTime            ;        
   TBranch *b_T_coin_pEL_HI_ROC2_tdcTimeRaw         ;        
   TBranch *b_T_coin_pEL_LO_LO_ROC1_tdcMultiplicity ;        
   TBranch *b_T_coin_pEL_LO_LO_ROC1_tdcTime         ;        
   TBranch *b_T_coin_pEL_LO_LO_ROC1_tdcTimeRaw      ;        
   TBranch *b_T_coin_pEL_LO_LO_ROC2_tdcMultiplicity ;        
   TBranch *b_T_coin_pEL_LO_LO_ROC2_tdcTime         ;        
   TBranch *b_T_coin_pEL_LO_LO_ROC2_tdcTimeRaw      ;        
   TBranch *b_T_coin_pEL_LO_ROC1_tdcMultiplicity    ;        
   TBranch *b_T_coin_pEL_LO_ROC1_tdcTime            ;        
   TBranch *b_T_coin_pEL_LO_ROC1_tdcTimeRaw         ;        
   TBranch *b_T_coin_pEL_LO_ROC2_tdcMultiplicity    ;        
   TBranch *b_T_coin_pEL_LO_ROC2_tdcTime            ;        
   TBranch *b_T_coin_pEL_LO_ROC2_tdcTimeRaw         ;        
   TBranch *b_T_coin_pEL_REAL_ROC1_tdcMultiplicity  ;        
   TBranch *b_T_coin_pEL_REAL_ROC1_tdcTime          ;        
   TBranch *b_T_coin_pEL_REAL_ROC1_tdcTimeRaw       ;        
   TBranch *b_T_coin_pEL_REAL_ROC2_tdcMultiplicity  ;        
   TBranch *b_T_coin_pEL_REAL_ROC2_tdcTime          ;        
   TBranch *b_T_coin_pEL_REAL_ROC2_tdcTimeRaw       ;        
   TBranch *b_T_coin_pFADC_TREF_ROC2_adcMultiplicity;        
   TBranch *b_T_coin_pFADC_TREF_ROC2_adcPed         ;        
   TBranch *b_T_coin_pFADC_TREF_ROC2_adcPedRaw      ;        
   TBranch *b_T_coin_pFADC_TREF_ROC2_adcPulseAmp    ;        
   TBranch *b_T_coin_pFADC_TREF_ROC2_adcPulseAmpRaw ;        
   TBranch *b_T_coin_pFADC_TREF_ROC2_adcPulseInt    ;        
   TBranch *b_T_coin_pFADC_TREF_ROC2_adcPulseIntRaw ;        
   TBranch *b_T_coin_pFADC_TREF_ROC2_adcPulseTime   ;        
   TBranch *b_T_coin_pFADC_TREF_ROC2_adcPulseTimeRaw;        
   TBranch *b_T_coin_pHEL_MPS_adcMultiplicity       ;       
   TBranch *b_T_coin_pHEL_MPS_adcPed                ;       
   TBranch *b_T_coin_pHEL_MPS_adcPedRaw             ;       
   TBranch *b_T_coin_pHEL_MPS_adcPulseAmp           ;       
   TBranch *b_T_coin_pHEL_MPS_adcPulseAmpRaw        ;       
   TBranch *b_T_coin_pHEL_MPS_adcPulseInt           ;       
   TBranch *b_T_coin_pHEL_MPS_adcPulseIntRaw        ;       
   TBranch *b_T_coin_pHEL_MPS_adcPulseTime          ;       
   TBranch *b_T_coin_pHEL_MPS_adcPulseTimeRaw       ;       
   TBranch *b_T_coin_pHEL_NEG_adcMultiplicity       ;       
   TBranch *b_T_coin_pHEL_NEG_adcPed                ;       
   TBranch *b_T_coin_pHEL_NEG_adcPedRaw             ;       
   TBranch *b_T_coin_pHEL_NEG_adcPulseAmp           ;       
   TBranch *b_T_coin_pHEL_NEG_adcPulseAmpRaw        ;       
   TBranch *b_T_coin_pHEL_NEG_adcPulseInt           ;       
   TBranch *b_T_coin_pHEL_NEG_adcPulseIntRaw        ;       
   TBranch *b_T_coin_pHEL_NEG_adcPulseTime          ;       
   TBranch *b_T_coin_pHEL_NEG_adcPulseTimeRaw       ;       
   TBranch *b_T_coin_pHEL_POS_adcMultiplicity       ;       
   TBranch *b_T_coin_pHEL_POS_adcPed                ;       
   TBranch *b_T_coin_pHEL_POS_adcPedRaw             ;       
   TBranch *b_T_coin_pHEL_POS_adcPulseAmp           ;       
   TBranch *b_T_coin_pHEL_POS_adcPulseAmpRaw        ;       
   TBranch *b_T_coin_pHEL_POS_adcPulseInt           ;       
   TBranch *b_T_coin_pHEL_POS_adcPulseIntRaw        ;       
   TBranch *b_T_coin_pHEL_POS_adcPulseTime          ;       
   TBranch *b_T_coin_pHEL_POS_adcPulseTimeRaw       ;       
   TBranch *b_T_coin_pHGCER_MOD_adcMultiplicity     ;       
   TBranch *b_T_coin_pHGCER_MOD_adcPed              ;       
   TBranch *b_T_coin_pHGCER_MOD_adcPedRaw           ;       
   TBranch *b_T_coin_pHGCER_MOD_adcPulseAmp         ;       
   TBranch *b_T_coin_pHGCER_MOD_adcPulseAmpRaw      ;       
   TBranch *b_T_coin_pHGCER_MOD_adcPulseInt         ;       
   TBranch *b_T_coin_pHGCER_MOD_adcPulseIntRaw      ;       
   TBranch *b_T_coin_pHGCER_MOD_adcPulseTime        ;       
   TBranch *b_T_coin_pHGCER_MOD_adcPulseTimeRaw     ;       
   TBranch *b_T_coin_pHGCER_adcMultiplicity         ;      
   TBranch *b_T_coin_pHGCER_adcPed                  ;      
   TBranch *b_T_coin_pHGCER_adcPedRaw               ;      
   TBranch *b_T_coin_pHGCER_adcPulseAmp             ;      
   TBranch *b_T_coin_pHGCER_adcPulseAmpRaw          ;      
   TBranch *b_T_coin_pHGCER_adcPulseInt             ;      
   TBranch *b_T_coin_pHGCER_adcPulseIntRaw          ;      
   TBranch *b_T_coin_pHGCER_adcPulseTime            ;      
   TBranch *b_T_coin_pHGCER_adcPulseTimeRaw         ;      
   TBranch *b_T_coin_pHGCER_tdcMultiplicity         ;      
   TBranch *b_T_coin_pHGCER_tdcTime                 ;      
   TBranch *b_T_coin_pHGCER_tdcTimeRaw              ;      
   TBranch *b_T_coin_pHODO_RF_tdcMultiplicity       ;      
   TBranch *b_T_coin_pHODO_RF_tdcTime               ;      
   TBranch *b_T_coin_pHODO_RF_tdcTimeRaw            ;      
   TBranch *b_T_coin_pNGCER_MOD_adcMultiplicity     ;      
   TBranch *b_T_coin_pNGCER_MOD_adcPed              ;      
   TBranch *b_T_coin_pNGCER_MOD_adcPedRaw           ;      
   TBranch *b_T_coin_pNGCER_MOD_adcPulseAmp         ;      
   TBranch *b_T_coin_pNGCER_MOD_adcPulseAmpRaw      ;      
   TBranch *b_T_coin_pNGCER_MOD_adcPulseInt         ;      
   TBranch *b_T_coin_pNGCER_MOD_adcPulseIntRaw      ;      
   TBranch *b_T_coin_pNGCER_MOD_adcPulseTime        ;      
   TBranch *b_T_coin_pNGCER_MOD_adcPulseTimeRaw     ;      
   TBranch *b_T_coin_pNGCER_adcMultiplicity         ;      
   TBranch *b_T_coin_pNGCER_adcPed                  ;      
   TBranch *b_T_coin_pNGCER_adcPedRaw               ;      
   TBranch *b_T_coin_pNGCER_adcPulseAmp             ;      
   TBranch *b_T_coin_pNGCER_adcPulseAmpRaw          ;      
   TBranch *b_T_coin_pNGCER_adcPulseInt             ;      
   TBranch *b_T_coin_pNGCER_adcPulseIntRaw          ;      
   TBranch *b_T_coin_pNGCER_adcPulseTime            ;      
   TBranch *b_T_coin_pNGCER_adcPulseTimeRaw         ;      
   TBranch *b_T_coin_pNGCER_tdcMultiplicity         ;      
   TBranch *b_T_coin_pNGCER_tdcTime                 ;      
   TBranch *b_T_coin_pNGCER_tdcTimeRaw              ;      
   TBranch *b_T_coin_pPRE100_ROC1_tdcMultiplicity   ;      
   TBranch *b_T_coin_pPRE100_ROC1_tdcTime           ;      
   TBranch *b_T_coin_pPRE100_ROC1_tdcTimeRaw        ;      
   TBranch *b_T_coin_pPRE100_ROC2_tdcMultiplicity   ;      
   TBranch *b_T_coin_pPRE100_ROC2_tdcTime           ;      
   TBranch *b_T_coin_pPRE100_ROC2_tdcTimeRaw        ;      
   TBranch *b_T_coin_pPRE150_ROC1_tdcMultiplicity   ;      
   TBranch *b_T_coin_pPRE150_ROC1_tdcTime           ;      
   TBranch *b_T_coin_pPRE150_ROC1_tdcTimeRaw        ;      
   TBranch *b_T_coin_pPRE150_ROC2_tdcMultiplicity   ;      
   TBranch *b_T_coin_pPRE150_ROC2_tdcTime           ;      
   TBranch *b_T_coin_pPRE150_ROC2_tdcTimeRaw        ;      
   TBranch *b_T_coin_pPRE200_ROC1_tdcMultiplicity   ;      
   TBranch *b_T_coin_pPRE200_ROC1_tdcTime           ;      
   TBranch *b_T_coin_pPRE200_ROC1_tdcTimeRaw        ;      
   TBranch *b_T_coin_pPRE200_ROC2_tdcMultiplicity   ;      
   TBranch *b_T_coin_pPRE200_ROC2_tdcTime           ;      
   TBranch *b_T_coin_pPRE200_ROC2_tdcTimeRaw        ;      
   TBranch *b_T_coin_pPRE40_ROC1_tdcMultiplicity    ;      
   TBranch *b_T_coin_pPRE40_ROC1_tdcTime            ;     
   TBranch *b_T_coin_pPRE40_ROC1_tdcTimeRaw         ;     
   TBranch *b_T_coin_pPRE40_ROC2_tdcMultiplicity    ;     
   TBranch *b_T_coin_pPRE40_ROC2_tdcTime            ;     
   TBranch *b_T_coin_pPRE40_ROC2_tdcTimeRaw         ;     
   TBranch *b_T_coin_pPRHI_tdcMultiplicity          ;     
   TBranch *b_T_coin_pPRHI_tdcTime                  ;     
   TBranch *b_T_coin_pPRHI_tdcTimeRaw               ;     
   TBranch *b_T_coin_pPRLO_tdcMultiplicity          ;     
   TBranch *b_T_coin_pPRLO_tdcTime                  ;     
   TBranch *b_T_coin_pPRLO_tdcTimeRaw               ;     
   TBranch *b_T_coin_pPSHWR_adcMultiplicity         ;     
   TBranch *b_T_coin_pPSHWR_adcPed                  ;     
   TBranch *b_T_coin_pPSHWR_adcPedRaw               ;     
   TBranch *b_T_coin_pPSHWR_adcPulseAmp             ;     
   TBranch *b_T_coin_pPSHWR_adcPulseAmpRaw          ;     
   TBranch *b_T_coin_pPSHWR_adcPulseInt             ;     
   TBranch *b_T_coin_pPSHWR_adcPulseIntRaw          ;     
   TBranch *b_T_coin_pPSHWR_adcPulseTime            ;     
   TBranch *b_T_coin_pPSHWR_adcPulseTimeRaw         ;     
   TBranch *b_T_coin_pRF_tdcMultiplicity            ;     
   TBranch *b_T_coin_pRF_tdcTime                    ;     
   TBranch *b_T_coin_pRF_tdcTimeRaw                 ;     
   TBranch *b_T_coin_pSTOF_ROC1_tdcMultiplicity     ;     
   TBranch *b_T_coin_pSTOF_ROC1_tdcTime             ;     
   TBranch *b_T_coin_pSTOF_ROC1_tdcTimeRaw          ;     
   TBranch *b_T_coin_pSTOF_ROC2_tdcMultiplicity     ;     
   TBranch *b_T_coin_pSTOF_ROC2_tdcTime             ;     
   TBranch *b_T_coin_pSTOF_ROC2_tdcTimeRaw          ;     
   TBranch *b_T_coin_pT1_tdcMultiplicity            ;     
   TBranch *b_T_coin_pT1_tdcTime                    ;     
   TBranch *b_T_coin_pT1_tdcTimeRaw                 ;     
   TBranch *b_T_coin_pT2_tdcMultiplicity            ;     
   TBranch *b_T_coin_pT2_tdcTime                    ;     
   TBranch *b_T_coin_pT2_tdcTimeRaw                 ;     
   TBranch *b_T_coin_pT3_tdcMultiplicity            ;     
   TBranch *b_T_coin_pT3_tdcTime                    ;     
   TBranch *b_T_coin_pT3_tdcTimeRaw                 ;     
   TBranch *b_T_coin_pTRIG1_ROC1_tdcMultiplicity    ;     
   TBranch *b_T_coin_pTRIG1_ROC1_tdcTime            ;     
   TBranch *b_T_coin_pTRIG1_ROC1_tdcTimeRaw         ;     
   TBranch *b_T_coin_pTRIG1_ROC2_tdcMultiplicity    ;     
   TBranch *b_T_coin_pTRIG1_ROC2_tdcTime            ;     
   TBranch *b_T_coin_pTRIG1_ROC2_tdcTimeRaw         ;     
   TBranch *b_T_coin_pTRIG2_ROC1_tdcMultiplicity    ;     
   TBranch *b_T_coin_pTRIG2_ROC1_tdcTime            ;    
   TBranch *b_T_coin_pTRIG2_ROC1_tdcTimeRaw         ;    
   TBranch *b_T_coin_pTRIG2_ROC2_tdcMultiplicity    ;    
   TBranch *b_T_coin_pTRIG2_ROC2_tdcTime            ;    
   TBranch *b_T_coin_pTRIG2_ROC2_tdcTimeRaw         ;    
   TBranch *b_T_coin_pTRIG3_ROC1_tdcMultiplicity    ;    
   TBranch *b_T_coin_pTRIG3_ROC1_tdcTime            ;    
   TBranch *b_T_coin_pTRIG3_ROC1_tdcTimeRaw         ;    
   TBranch *b_T_coin_pTRIG3_ROC2_tdcMultiplicity    ;    
   TBranch *b_T_coin_pTRIG3_ROC2_tdcTime            ;    
   TBranch *b_T_coin_pTRIG3_ROC2_tdcTimeRaw         ;    
   TBranch *b_T_coin_pTRIG4_ROC1_tdcMultiplicity    ;    
   TBranch *b_T_coin_pTRIG4_ROC1_tdcTime            ;    
   TBranch *b_T_coin_pTRIG4_ROC1_tdcTimeRaw         ;    
   TBranch *b_T_coin_pTRIG4_ROC2_tdcMultiplicity    ;    
   TBranch *b_T_coin_pTRIG4_ROC2_tdcTime            ;    
   TBranch *b_T_coin_pTRIG4_ROC2_tdcTimeRaw         ;    
   TBranch *b_T_coin_pTRIG5_ROC1_tdcMultiplicity    ;    
   TBranch *b_T_coin_pTRIG5_ROC1_tdcTime            ;    
   TBranch *b_T_coin_pTRIG5_ROC1_tdcTimeRaw         ;    
   TBranch *b_T_coin_pTRIG5_ROC2_tdcMultiplicity    ;    
   TBranch *b_T_coin_pTRIG5_ROC2_tdcTime            ;    
   TBranch *b_T_coin_pTRIG5_ROC2_tdcTimeRaw         ;    
   TBranch *b_T_coin_pTRIG6_ROC1_tdcMultiplicity    ;    
   TBranch *b_T_coin_pTRIG6_ROC1_tdcTime            ;    
   TBranch *b_T_coin_pTRIG6_ROC1_tdcTimeRaw         ;    
   TBranch *b_T_coin_pTRIG6_ROC2_tdcMultiplicity    ;    
   TBranch *b_T_coin_pTRIG6_ROC2_tdcTime            ;   
   TBranch *b_T_coin_pTRIG6_ROC2_tdcTimeRaw         ;   
   TBranch *b_g_evtyp                               ;   
   TBranch *b_IPM3H07A_XPOS                         ;   
   TBranch *b_IPM3H07A_YPOS                         ;   
   TBranch *b_IPM3H07B_XPOS                         ;   
   TBranch *b_IPM3H07B_YPOS                         ;   
   TBranch *b_IPM3H07C_XPOS                         ;   
   TBranch *b_IPM3H07C_YPOS                         ;   
   TBranch *b_IPM3H07A_XRAW                         ;   
   TBranch *b_IPM3H07A_YRAW                         ;   
   TBranch *b_IPM3H07B_XRAW                         ;   
   TBranch *b_IPM3H07B_YRAW                         ;   
   TBranch *b_IPM3H07C_XRAW                         ;   
   TBranch *b_IPM3H07C_YRAW                         ;   
   TBranch *b_IPM3H07A_XSOF                         ;   
   TBranch *b_IPM3H07A_YSOF                         ;   
   TBranch *b_IPM3H07B_XSOF                         ;   
   TBranch *b_IPM3H07B_YSOF                         ;   
   TBranch *b_IPM3H07C_XSOF                         ;   
   TBranch *b_IPM3H07C_YSOF                         ;   
   TBranch *b_fEvtHdr_fEvtTime                      ; 
   TBranch *b_fEvtHdr_fEvtNum                       ;  
   TBranch *b_fEvtHdr_fEvtType                      ;  
   TBranch *b_fEvtHdr_fEvtLen                       ;  
   TBranch *b_fEvtHdr_fHelicity                     ;  
   TBranch *b_fEvtHdr_fTargetPol                    ;  
   TBranch *b_fEvtHdr_fRun                          ;  
   TBranch *b_IBC3H00CRCUR4                         ;   
   TBranch *b_IGL1I00OD16_16                        ;   
   TBranch *b_HELFREQ                               ;   
   TBranch *b_HELDELAYs                             ;   
   TBranch *b_hac_bcm_average                       ;   
   TBranch *b_ibcm1                                 ;   
   TBranch *b_ibcm2                                 ;   
   TBranch *b_iunser                                ;   
   TBranch *b_itov3out                              ;   
   TBranch *b_itov4out                              ;   

   TBranch *b_Event_Branch  ;                        ;   
   TBranch *b_Event_Branch_fEvtHdr_fEvtTime;
   TBranch *b_Event_Branch_fEvtHdr_fEvtNum;
   TBranch *b_Event_Branch_fEvtHdr_fEvtType;
   TBranch *b_Event_Branch_fEvtHdr_fEvtLen;
   TBranch *b_Event_Branch_fEvtHdr_fHelicity;
   TBranch *b_Event_Branch_fEvtHdr_fTargetPol;
   TBranch *b_Event_Branch_fEvtHdr_fRun;


};

#endif

